'use client';

import React, { useEffect, useState, useCallback, useRef } from 'react';
import { X, Check, XCircle, Sparkles } from 'lucide-react';
import TiptapEditor from '@/components/editor/tiptap-editor';
import type { Note } from '@/lib/notes';

interface EditorPanelProps {
  noteId: string;
  onClose: () => void;
}

type SuggestedLink = {
  linkId: string;
  noteId: string;
  noteTitle: string;
  strength: number;
};

export default function EditorPanel({ noteId, onClose }: EditorPanelProps) {
  const [note, setNote] = useState<Note | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);
  const [backlinks, setBacklinks] = useState<Note[]>([]);
  const [suggestedLinks, setSuggestedLinks] = useState<SuggestedLink[]>([]);
  const autoSaveRef = useRef<NodeJS.Timeout | undefined>(undefined);

  // Fetch note, backlinks, and suggested links
  useEffect(() => {
    const fetchNote = async () => {
      setIsLoading(true);
      try {
        const [noteRes, backlinksRes, graphRes] = await Promise.all([
          fetch(`/api/notes/${noteId}`),
          fetch(`/api/notes/${noteId}/backlinks`),
          fetch('/api/graph'),
        ]);

        if (noteRes.ok) {
          setNote(await noteRes.json());
        }
        if (backlinksRes.ok) {
          setBacklinks(await backlinksRes.json());
        }

        // Extract auto-generated links for this note from graph data
        if (graphRes.ok) {
          const graph = await graphRes.json();
          const autoLinks: SuggestedLink[] = [];

          for (const link of graph.links) {
            if (!link.autoGenerated) continue;

            let otherNoteId: string | null = null;
            if (link.source === noteId) otherNoteId = link.target;
            else if (link.target === noteId) otherNoteId = link.source;
            if (!otherNoteId) continue;

            const otherNode = graph.nodes.find((n: { id: string }) => n.id === otherNoteId);
            if (otherNode) {
              autoLinks.push({
                linkId: link.id,
                noteId: otherNode.id,
                noteTitle: otherNode.title,
                strength: link.strength,
              });
            }
          }

          setSuggestedLinks(autoLinks);
        }
      } catch (err) {
        console.error('Failed to fetch note:', err);
      } finally {
        setIsLoading(false);
      }
    };

    fetchNote();
  }, [noteId]);

  // Auto-save
  const saveNote = useCallback(
    async (updated: Note) => {
      setIsSaving(true);
      try {
        const response = await fetch(`/api/notes/${noteId}`, {
          method: 'PUT',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            title: updated.title,
            content: updated.content,
          }),
        });
        if (response.ok) {
          const saved = await response.json();
          setNote(saved);
        }
      } catch (err) {
        console.error('Failed to save:', err);
      } finally {
        setIsSaving(false);
      }
    },
    [noteId]
  );

  const scheduleSave = useCallback(
    (updated: Note) => {
      if (autoSaveRef.current) clearTimeout(autoSaveRef.current);
      autoSaveRef.current = setTimeout(() => saveNote(updated), 1000);
    },
    [saveNote]
  );

  const handleTitleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (!note) return;
    const updated = { ...note, title: e.target.value };
    setNote(updated);
    scheduleSave(updated);
  };

  const handleContentChange = (content: string) => {
    if (!note) return;
    const updated = { ...note, content };
    setNote(updated);
    scheduleSave(updated);
  };

  // Handle accept/dismiss for suggested links
  const handleLinkAction = useCallback(
    async (linkId: string, action: 'accept' | 'dismiss') => {
      try {
        const res = await fetch(`/api/links/${linkId}`, {
          method: 'PATCH',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ action }),
        });
        if (res.ok) {
          setSuggestedLinks((prev) => prev.filter((l) => l.linkId !== linkId));
        }
      } catch (err) {
        console.error(`Failed to ${action} link:`, err);
      }
    },
    []
  );

  // Close on Escape
  useEffect(() => {
    const handleKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    };
    window.addEventListener('keydown', handleKey);
    return () => window.removeEventListener('keydown', handleKey);
  }, [onClose]);

  return (
    <div
      className="
        absolute top-0 right-0 h-full
        w-full sm:w-[480px] md:w-[520px] lg:w-[560px]
        bg-[var(--color-surface)]
        border-l border-[var(--color-border)]
        shadow-2xl
        flex flex-col
        z-30
        animate-slide-in
      "
      onClick={(e) => e.stopPropagation()}
    >
      {/* Header */}
      <div className="flex items-center gap-2 px-4 py-3 border-b border-[var(--color-border)]">
        <button
          onClick={onClose}
          className="p-1.5 rounded hover:bg-[var(--color-surface-secondary)] transition-colors"
          title="Close (Esc)"
        >
          <X className="w-4 h-4 text-[var(--color-foreground-secondary)]" />
        </button>
        <div className="flex-1 text-xs text-[var(--color-foreground-secondary)]">
          {isSaving ? 'Saving...' : isLoading ? '' : 'Saved'}
        </div>
      </div>

      {isLoading ? (
        <div className="flex-1 flex items-center justify-center text-[var(--color-foreground-secondary)]">
          Loading...
        </div>
      ) : !note ? (
        <div className="flex-1 flex items-center justify-center text-[var(--color-foreground-secondary)]">
          Note not found
        </div>
      ) : (
        <>
          {/* Title */}
          <div className="px-4 pt-4 pb-2">
            <input
              type="text"
              value={note.title}
              onChange={handleTitleChange}
              placeholder="Untitled Note"
              className="
                w-full text-2xl font-bold bg-transparent
                text-[var(--color-foreground)]
                placeholder-[var(--color-foreground-secondary)]
                outline-none
              "
            />
          </div>

          {/* Editor */}
          <div className="flex-1 overflow-y-auto">
            <TiptapEditor
              content={note.content}
              onChange={handleContentChange}
              editable={true}
            />
          </div>

          {/* Suggested Links (auto-generated) */}
          {suggestedLinks.length > 0 && (
            <div className="border-t border-[var(--color-border)] px-4 py-3">
              <div className="flex items-center gap-1.5 mb-2">
                <Sparkles className="w-3 h-3 text-[var(--color-accent-secondary)]" />
                <span className="text-xs font-semibold text-[var(--color-foreground-secondary)]">
                  Suggested Links ({suggestedLinks.length})
                </span>
              </div>
              <div className="space-y-1.5 max-h-40 overflow-y-auto">
                {suggestedLinks.map((sl) => (
                  <div
                    key={sl.linkId}
                    className="flex items-center gap-2 group"
                  >
                    <span className="text-xs text-[var(--color-accent)] truncate flex-1">
                      {sl.noteTitle}
                    </span>
                    <span className="text-[10px] text-[var(--color-muted)] shrink-0">
                      {Math.round(sl.strength * 100)}%
                    </span>
                    <button
                      onClick={() => handleLinkAction(sl.linkId, 'accept')}
                      className="p-0.5 rounded hover:bg-[var(--color-surface-secondary)] opacity-0 group-hover:opacity-100 transition-opacity"
                      title="Accept link"
                    >
                      <Check className="w-3 h-3 text-[var(--color-success)]" />
                    </button>
                    <button
                      onClick={() => handleLinkAction(sl.linkId, 'dismiss')}
                      className="p-0.5 rounded hover:bg-[var(--color-surface-secondary)] opacity-0 group-hover:opacity-100 transition-opacity"
                      title="Dismiss link"
                    >
                      <XCircle className="w-3 h-3 text-[var(--color-danger)]" />
                    </button>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Backlinks */}
          {backlinks.length > 0 && (
            <div className="border-t border-[var(--color-border)] px-4 py-3">
              <div className="text-xs font-semibold text-[var(--color-foreground-secondary)] mb-2">
                Backlinks ({backlinks.length})
              </div>
              <div className="space-y-1 max-h-32 overflow-y-auto">
                {backlinks.map((bl) => (
                  <div
                    key={bl.id}
                    className="text-xs text-[var(--color-accent)] truncate cursor-pointer hover:underline"
                  >
                    {bl.title}
                  </div>
                ))}
              </div>
            </div>
          )}
        </>
      )}
    </div>
  );
}
