'use client';

import React, { useRef, useState, useEffect, useCallback, useMemo } from 'react';
import dynamic from 'next/dynamic';
import type { GraphData } from '@/app/api/graph/route';
import { drawCreature, drawLink, getCreatureSize } from './creature-renderer';
import type { CreatureNode } from './creature-renderer';

// react-force-graph-2d uses Canvas and must be client-only
const ForceGraph2D = dynamic(() => import('react-force-graph-2d'), {
  ssr: false,
  loading: () => (
    <div className="flex-1 flex items-center justify-center text-[var(--color-foreground-secondary)]">
      Growing your garden...
    </div>
  ),
});

type TerrariumNode = CreatureNode & {
  __indexColor?: string;
};

type TerrariumLink = {
  id: string;
  source: string | TerrariumNode;
  target: string | TerrariumNode;
  autoGenerated: boolean;
  strength: number;
};

type ForceGraphData = {
  nodes: TerrariumNode[];
  links: TerrariumLink[];
};

interface TerrariumProps {
  onSelectNote: (noteId: string) => void;
  selectedNoteId: string | null;
  onNoteCountChange?: (count: number) => void;
}

export default function Terrarium({ onSelectNote, selectedNoteId, onNoteCountChange }: TerrariumProps) {
  const graphRef = useRef<any>(null);
  const containerRef = useRef<HTMLDivElement>(null);
  const [graphData, setGraphData] = useState<ForceGraphData>({ nodes: [], links: [] });
  const [hoveredNode, setHoveredNode] = useState<string | null>(null);
  const [dimensions, setDimensions] = useState({ width: 800, height: 600 });
  const [isLoading, setIsLoading] = useState(true);
  const animationRef = useRef<number | null>(null);

  // Fetch graph data
  const fetchGraph = useCallback(async () => {
    try {
      const response = await fetch('/api/graph');
      if (!response.ok) return;

      const data: GraphData = await response.json();

      const nodes = data.nodes.map((n) => ({
        id: n.id,
        title: n.title,
        contentLength: n.contentLength,
        createdAt: n.createdAt,
        updatedAt: n.updatedAt,
        tags: n.tags,
      }));

      setGraphData({
        nodes,
        links: data.links.map((l) => ({
          id: l.id,
          source: l.source,
          target: l.target,
          autoGenerated: l.autoGenerated,
          strength: l.strength,
        })),
      });

      onNoteCountChange?.(nodes.length);
    } catch (error) {
      console.error('Failed to fetch graph:', error);
    } finally {
      setIsLoading(false);
    }
  }, [onNoteCountChange]);

  useEffect(() => {
    fetchGraph();
  }, [fetchGraph]);

  // Re-fetch when a note changes (simple polling for now)
  useEffect(() => {
    const interval = setInterval(fetchGraph, 10000);
    return () => clearInterval(interval);
  }, [fetchGraph]);

  // Responsive sizing
  useEffect(() => {
    const handleResize = () => {
      if (containerRef.current) {
        setDimensions({
          width: containerRef.current.clientWidth,
          height: containerRef.current.clientHeight,
        });
      }
    };

    handleResize();
    window.addEventListener('resize', handleResize);

    // ResizeObserver for container changes (e.g., editor panel opening)
    const observer = new ResizeObserver(handleResize);
    if (containerRef.current) observer.observe(containerRef.current);

    return () => {
      window.removeEventListener('resize', handleResize);
      observer.disconnect();
    };
  }, []);

  // Continuous animation tick for breathing effect
  useEffect(() => {
    const tick = () => {
      if (graphRef.current) {
        // Force a re-render of the canvas for breathing animations
        graphRef.current.d3ReheatSimulation?.();
      }
      animationRef.current = requestAnimationFrame(tick);
    };

    // Only start breathing animation after initial layout settles
    const timer = setTimeout(() => {
      animationRef.current = requestAnimationFrame(tick);
    }, 3000);

    return () => {
      clearTimeout(timer);
      if (animationRef.current) cancelAnimationFrame(animationRef.current);
    };
  }, []);

  // Configure force simulation
  useEffect(() => {
    if (graphRef.current) {
      const fg = graphRef.current;
      // Spread nodes out more
      fg.d3Force('charge')?.strength(-120);
      fg.d3Force('link')?.distance(80);
      fg.d3Force('center')?.strength(0.05);
    }
  }, [graphData]);

  // Custom node drawing
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const nodeCanvasObject = useCallback(
    (node: any, ctx: CanvasRenderingContext2D, globalScale: number) => {
      const n = node as TerrariumNode;
      drawCreature(
        n,
        ctx,
        globalScale,
        hoveredNode === n.id,
        selectedNoteId === n.id
      );
    },
    [hoveredNode, selectedNoteId]
  );

  // Custom link drawing
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const linkCanvasObject = useCallback(
    (link: any, ctx: CanvasRenderingContext2D, globalScale: number) => {
      drawLink(link, ctx, globalScale);
    },
    []
  );

  // Node click area
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const nodePointerAreaPaint = useCallback(
    (node: any, color: string, ctx: CanvasRenderingContext2D) => {
      const n = node as TerrariumNode;
      const size = getCreatureSize(n.contentLength);
      ctx.fillStyle = color;
      ctx.beginPath();
      ctx.arc(n.x || 0, n.y || 0, size + 4, 0, Math.PI * 2);
      ctx.fill();
    },
    []
  );

  // Node interactions
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const handleNodeClick = useCallback(
    (node: any) => {
      onSelectNote((node as TerrariumNode).id);
    },
    [onSelectNote]
  );

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const handleNodeHover = useCallback((node: any) => {
    const n = node as TerrariumNode | null;
    setHoveredNode(n?.id || null);
    if (containerRef.current) {
      containerRef.current.style.cursor = n ? 'pointer' : 'default';
    }
  }, []);

  // Background click to deselect
  const handleBackgroundClick = useCallback(() => {
    // Only deselect if clicking empty space
    if (!hoveredNode) {
      onSelectNote('');
    }
  }, [hoveredNode, onSelectNote]);

  if (isLoading) {
    return (
      <div
        ref={containerRef}
        className="flex-1 min-h-0 flex items-center justify-center bg-[#0a0a0f]"
      >
        <div className="text-center">
          <div className="text-[var(--color-foreground-secondary)] text-lg">
            Growing your garden...
          </div>
        </div>
      </div>
    );
  }

  return (
    <div
      ref={containerRef}
      className="flex-1 min-h-0 relative bg-[#0a0a0f] overflow-hidden"
      onClick={handleBackgroundClick}
    >
      {graphData.nodes.length === 0 ? (
        <div className="absolute inset-0 flex items-center justify-center">
          <div className="text-center">
            <div className="text-6xl mb-4 opacity-30">🌱</div>
            <h2 className="text-xl font-semibold text-[var(--color-foreground)] mb-2">
              Your Garden is Empty
            </h2>
            <p className="text-[var(--color-foreground-secondary)] text-sm">
              Plant your first seed to start growing
            </p>
          </div>
        </div>
      ) : (
        <ForceGraph2D
          ref={graphRef}
          width={dimensions.width}
          height={dimensions.height}
          graphData={graphData}
          // Rendering
          nodeCanvasObject={nodeCanvasObject}
          nodePointerAreaPaint={nodePointerAreaPaint}
          linkCanvasObject={linkCanvasObject}
          // Interactions
          onNodeClick={handleNodeClick}
          onNodeHover={handleNodeHover}
          // Layout
          cooldownTicks={100}
          d3AlphaDecay={0.02}
          d3VelocityDecay={0.3}
          // Style
          backgroundColor="#0a0a0f"
          enableNodeDrag={true}
          enableZoomInteraction={true}
          enablePanInteraction={true}
          minZoom={0.3}
          maxZoom={5}
        />
      )}

      {/* Tooltip */}
      {hoveredNode && (
        <HoverTooltip
          node={graphData.nodes.find((n) => n.id === hoveredNode) || null}
        />
      )}
    </div>
  );
}

// Simple tooltip that follows mouse
function HoverTooltip({ node }: { node: TerrariumNode | null }) {
  const [pos, setPos] = useState({ x: 0, y: 0 });

  useEffect(() => {
    const handleMove = (e: MouseEvent) => {
      setPos({ x: e.clientX + 12, y: e.clientY - 12 });
    };
    window.addEventListener('mousemove', handleMove);
    return () => window.removeEventListener('mousemove', handleMove);
  }, []);

  if (!node) return null;

  const daysSinceUpdate = Math.floor(
    (Date.now() - new Date(node.updatedAt).getTime()) / (1000 * 60 * 60 * 24)
  );
  const freshness =
    daysSinceUpdate === 0
      ? 'Updated today'
      : daysSinceUpdate === 1
        ? 'Updated yesterday'
        : `Updated ${daysSinceUpdate}d ago`;

  return (
    <div
      className="fixed z-50 pointer-events-none px-3 py-2 rounded-lg
        bg-[var(--color-surface)] border border-[var(--color-border)]
        shadow-lg max-w-[240px]"
      style={{ left: pos.x, top: pos.y }}
    >
      <div className="text-sm font-semibold text-[var(--color-foreground)] truncate">
        {node.title}
      </div>
      <div className="text-xs text-[var(--color-foreground-secondary)] mt-1">
        {freshness}
      </div>
      {node.tags.length > 0 && (
        <div className="flex gap-1 mt-1 flex-wrap">
          {node.tags.slice(0, 3).map((tag) => (
            <span
              key={tag}
              className="text-[10px] px-1.5 py-0.5 rounded bg-[var(--color-surface-secondary)] text-[var(--color-foreground-secondary)]"
            >
              {tag}
            </span>
          ))}
        </div>
      )}
    </div>
  );
}
