// =============================================================
// MTR-293: System Template Seed Data
// 8 curated templates with realistic sections & AI prompts
// =============================================================

import type { Template, TemplateStyling } from './types';

const defaultStyling: TemplateStyling = {
  primary_color: '#2563eb',
  font_family: 'Inter',
  header_style: 'modern',
  show_logo: true,
};

// ---- Template 1: Standard Proposal (Pro) ----
export const TEMPLATE_STANDARD_PROPOSAL: Omit<Template, 'id' | 'created_at' | 'updated_at'> = {
  type: 'proposal',
  name: 'Standard Proposal',
  description: 'Professional proposal template for project pitches and scope discussions',
  category: 'general',
  is_system: true,
  freelancer_id: null,
  tier_required: 'pro',
  default_file_type: 'pdf',
  styling: defaultStyling,
  sections: [
    {
      key: 'executive_summary',
      label: 'Executive Summary',
      type: 'rich_text',
      required: true,
      ai_prompt: 'Write a compelling 2-3 sentence executive summary for this proposal that highlights the key value proposition for {client_name}. Focus on what problem we\'re solving and the expected outcome.',
      placeholder: 'A brief overview of the proposed solution and its benefits...',
    },
    {
      key: 'project_scope',
      label: 'Project Scope',
      type: 'rich_text',
      required: true,
      ai_prompt: 'Describe the scope of work for the "{project_name}" project. Be specific about what is included, the project boundaries, and key assumptions. Keep it concise but comprehensive.',
      placeholder: 'Define what is and isn\'t included in this project...',
    },
    {
      key: 'deliverables',
      label: 'Deliverables',
      type: 'list',
      required: true,
      ai_prompt: 'List the concrete deliverables for this project. For each item, provide a brief description. Examples: design files, code repositories, documentation, training materials, etc.',
      placeholder: 'e.g., Homepage design mockups, API documentation, User testing report',
    },
    {
      key: 'timeline',
      label: 'Timeline & Milestones',
      type: 'rich_text',
      required: true,
      ai_prompt: 'Create a realistic project timeline for {project_name} with key milestones. Break it into phases if appropriate and provide estimated durations.',
      placeholder: 'Project starts {project_start_date}. Phase 1 (2 weeks): Discovery & planning...',
    },
    {
      key: 'pricing',
      label: 'Pricing & Payment Terms',
      type: 'table',
      required: true,
      ai_prompt: 'Create a detailed pricing breakdown for this project. Include line items for different phases or deliverables, quantities, rates, and totals. Provide payment terms (e.g., 50% upfront, 50% on completion).',
      placeholder: 'Phase 1 Design | 2 weeks | $5,000 | Due upon completion',
    },
    {
      key: 'terms',
      label: 'Terms & Conditions',
      type: 'rich_text',
      required: true,
      ai_prompt: 'Write professional terms and conditions for this engagement. Cover: revision limits, intellectual property ownership, payment terms, cancellation policy, and dispute resolution.',
      placeholder: 'Client may request up to 2 rounds of revisions per phase. Ownership transfers upon full payment...',
    },
    {
      key: 'next_steps',
      label: 'Next Steps',
      type: 'list',
      required: true,
      ai_prompt: 'List the next steps to move forward with this proposal. Include action items for both parties and a timeline for decision-making.',
      placeholder: 'e.g., Schedule kickoff meeting, Review and approve contract, Transfer deposit payment',
    },
  ],
  metadata_schema: {
    total_price: { type: 'number', min: 0 },
    budget: { type: 'string' },
    timeline: { type: 'string' },
    terms: { type: 'string' },
    payment_terms: { type: 'string' },
  },
};

// ---- Template 2: Simple Invoice (Pro) ----
export const TEMPLATE_SIMPLE_INVOICE: Omit<Template, 'id' | 'created_at' | 'updated_at'> = {
  type: 'invoice',
  name: 'Simple Invoice',
  description: 'Clean, straightforward invoice template for billing clients',
  category: 'general',
  is_system: true,
  freelancer_id: null,
  tier_required: 'pro',
  default_file_type: 'pdf',
  styling: defaultStyling,
  sections: [
    {
      key: 'line_items',
      label: 'Line Items',
      type: 'table',
      required: true,
      ai_prompt: 'Create line items for the invoice to {client_name}. Include description of work/product, quantity, rate per unit, and calculate the total. Format: "Description | Qty | Rate | Amount"',
      placeholder: 'Design Services | 40 hours | $100/hr | $4,000\nRevisions | 5 hours | $100/hr | $500',
    },
    {
      key: 'payment_terms',
      label: 'Payment Terms',
      type: 'text',
      required: true,
      ai_prompt: 'Specify payment terms for this invoice. Include due date (e.g., Net 30), accepted payment methods, and any late payment penalties or early payment discounts.',
      placeholder: 'Due within 30 days of invoice date. Accept bank transfer, credit card, or PayPal.',
    },
    {
      key: 'notes',
      label: 'Additional Notes',
      type: 'rich_text',
      required: false,
      ai_prompt: 'Add any notes or special instructions for this invoice, such as project references, thank you messages, or next steps.',
      placeholder: 'Thank you for the opportunity to work with you on {project_name}. Please reference invoice number in payment.',
    },
    {
      key: 'bank_details',
      label: 'Bank Details',
      type: 'rich_text',
      required: false,
      ai_prompt: 'Provide bank account details for receiving payment. Include account holder name, bank name, account number, and routing number (for US accounts). For international transfers, include IBAN/SWIFT code.',
      placeholder: 'Account Holder: [Your Name]\nBank: [Bank Name]\nAccount: [Account Number]\nRouting: [Routing Number]',
    },
  ],
  metadata_schema: {
    line_items: { type: 'array' },
    total: { type: 'number', min: 0 },
    due_date: { type: 'string', format: 'date' },
    paid_at: { type: 'string', format: 'date-time', nullable: true },
    payment_terms: { type: 'string' },
  },
};

// ---- Template 3: Basic Contract (Pro) ----
export const TEMPLATE_BASIC_CONTRACT: Omit<Template, 'id' | 'created_at' | 'updated_at'> = {
  type: 'contract',
  name: 'Basic Contract',
  description: 'Foundational contract template covering essential legal clauses',
  category: 'general',
  is_system: true,
  freelancer_id: null,
  tier_required: 'pro',
  default_file_type: 'pdf',
  styling: defaultStyling,
  sections: [
    {
      key: 'parties',
      label: 'Parties to the Agreement',
      type: 'rich_text',
      required: true,
      ai_prompt: 'Identify the parties entering into this agreement. Include full legal names, addresses, and roles (Client/Service Provider). Format: "This Agreement is entered into between [Your Company] ("Provider") and {client_name} ("Client")"',
      placeholder: 'This Agreement is entered into between [Your Business] ("Provider") and {client_name} ("Client")...',
    },
    {
      key: 'scope_of_work',
      label: 'Scope of Work',
      type: 'rich_text',
      required: true,
      ai_prompt: 'Define the scope of work for the {project_name} project. Be specific about deliverables, timelines, and success criteria. Include what is NOT included in scope.',
      placeholder: 'Provider agrees to deliver: [list deliverables]. Timeline: [start date] to [end date].',
    },
    {
      key: 'deliverables',
      label: 'Deliverables',
      type: 'list',
      required: true,
      ai_prompt: 'List all deliverables for this engagement. Be specific and measurable.',
      placeholder: 'e.g., Final design files in Figma, Production-ready code on GitHub, Handoff documentation',
    },
    {
      key: 'timeline',
      label: 'Timeline & Milestones',
      type: 'rich_text',
      required: true,
      ai_prompt: 'Specify project timeline with key milestones and acceptance criteria for each phase.',
      placeholder: 'Project begins [date]. Phase 1 (weeks 1-2): Discovery. Phase 2 (weeks 3-5): Implementation...',
    },
    {
      key: 'compensation',
      label: 'Compensation & Payment',
      type: 'rich_text',
      required: true,
      ai_prompt: 'Detail the total compensation, payment schedule, and terms. Include currency, payment method, and when invoices will be issued.',
      placeholder: 'Total engagement fee: ${amount}. Payment: 50% upon signing, 50% upon completion. Invoice issued upon each milestone.',
    },
    {
      key: 'intellectual_property',
      label: 'Intellectual Property Rights',
      type: 'rich_text',
      required: true,
      ai_prompt: 'Specify IP ownership. State whether Client owns deliverables upon payment, or if Provider retains rights. Address use of pre-existing IP.',
      placeholder: 'Upon full payment, Client owns all custom work created under this Agreement. Provider retains rights to methodologies and pre-existing tools.',
    },
    {
      key: 'termination',
      label: 'Termination & Cancellation',
      type: 'rich_text',
      required: true,
      ai_prompt: 'Define termination conditions. Include notice periods, cancellation fees, and what happens to work-in-progress.',
      placeholder: 'Either party may terminate with 14 days written notice. Client responsible for payment up to termination date.',
    },
    {
      key: 'liability',
      label: 'Limitation of Liability',
      type: 'rich_text',
      required: true,
      ai_prompt: 'Draft liability limitations. Address warranties, indemnification, and exclude liability for indirect damages.',
      placeholder: 'Provider\'s liability limited to amount paid under this Agreement. Provider not liable for indirect or consequential damages.',
    },
    {
      key: 'governing_law',
      label: 'Governing Law & Disputes',
      type: 'rich_text',
      required: true,
      ai_prompt: 'Specify governing law jurisdiction and dispute resolution process. Include choice of venue and mediation/arbitration preferences.',
      placeholder: 'This Agreement governed by the laws of [State/Country]. Disputes resolved through mediation, then arbitration if needed.',
    },
    {
      key: 'signatures',
      label: 'Signatures & Execution',
      type: 'rich_text',
      required: false,
      ai_prompt: 'Add signature blocks for authorized representatives of both parties. Include name, title, and date fields.',
      placeholder: 'Provider: [Name/Title] Date: ____\nClient: [Name/Title] Date: ____',
    },
  ],
  metadata_schema: {
    clauses: { type: 'array' },
    signature_name: { type: 'string', nullable: true },
    signature_ip: { type: 'string', nullable: true },
    signed_at: { type: 'string', format: 'date-time', nullable: true },
  },
};

// ---- Template 4: Project Brief (Pro) ----
export const TEMPLATE_PROJECT_BRIEF: Omit<Template, 'id' | 'created_at' | 'updated_at'> = {
  type: 'brief',
  name: 'Project Brief',
  description: 'Concise project brief for scoping and alignment with stakeholders',
  category: 'general',
  is_system: true,
  freelancer_id: null,
  tier_required: 'pro',
  default_file_type: 'pdf',
  styling: defaultStyling,
  sections: [
    {
      key: 'project_overview',
      label: 'Project Overview',
      type: 'rich_text',
      required: true,
      ai_prompt: 'Provide a high-level overview of the {project_name} project for {client_name}. Explain the context and business need in 2-3 sentences.',
      placeholder: 'We are launching a mobile app to help users track their fitness goals. This project builds on our existing web platform and targets iOS and Android.',
    },
    {
      key: 'objectives',
      label: 'Project Objectives',
      type: 'list',
      required: true,
      ai_prompt: 'List 3-5 clear objectives for this project. Each should be specific and measurable.',
      placeholder: 'e.g., Increase user engagement by 40%, Reduce sign-up friction, Implement real-time notifications',
    },
    {
      key: 'target_audience',
      label: 'Target Audience',
      type: 'rich_text',
      required: true,
      ai_prompt: 'Describe the primary and secondary target audiences for this project. Include demographics, use cases, and pain points.',
      placeholder: 'Primary: Fitness enthusiasts aged 25-45. Secondary: Personal trainers. Key pain point: Manual workout tracking.',
    },
    {
      key: 'requirements',
      label: 'Requirements & Features',
      type: 'list',
      required: true,
      ai_prompt: 'List functional requirements and features. Categorize as "must-have", "should-have", or "nice-to-have".',
      placeholder: 'Must-have: User authentication, Workout logging, Progress tracking\nShould-have: Social sharing, Trainer messaging',
    },
    {
      key: 'constraints',
      label: 'Constraints & Limitations',
      type: 'rich_text',
      required: true,
      ai_prompt: 'Identify any constraints such as budget, timeline, technology stack, or resource limitations.',
      placeholder: 'Timeline: 12 weeks. Budget: $50k. Must integrate with existing payment system. Team: 2 developers.',
    },
    {
      key: 'success_criteria',
      label: 'Success Criteria',
      type: 'list',
      required: true,
      ai_prompt: 'Define measurable success criteria for this project. How will we know it succeeded?',
      placeholder: 'e.g., 1000 active users within 30 days, 4.5+ star app rating, 80% feature adoption',
    },
    {
      key: 'budget_range',
      label: 'Budget & Timeline',
      type: 'text',
      required: false,
      ai_prompt: 'Provide budget range and expected timeline for the project.',
      placeholder: 'Budget: $40,000 - $60,000. Timeline: 10-12 weeks. Start: [date]',
    },
  ],
  metadata_schema: {
    objectives: { type: 'array' },
    target_audience: { type: 'string' },
    tone: { type: 'string' },
    constraints: { type: 'array' },
  },
};

// ---- Template 5: Detailed SOW (Pro) ----
export const TEMPLATE_DETAILED_SOW: Omit<Template, 'id' | 'created_at' | 'updated_at'> = {
  type: 'sow',
  name: 'Detailed Statement of Work',
  description: 'Comprehensive SOW with detailed phases, milestones, and acceptance criteria',
  category: 'development',
  is_system: true,
  freelancer_id: null,
  tier_required: 'pro',
  default_file_type: 'pdf',
  styling: defaultStyling,
  sections: [
    {
      key: 'project_overview',
      label: 'Project Overview',
      type: 'rich_text',
      required: true,
      ai_prompt: 'Write a comprehensive overview of the {project_name} project for {client_name}. Include background, goals, and strategic importance.',
      placeholder: 'Project Overview:\n[Project name] represents a critical initiative to [strategic goal]. This engagement will [describe scope].',
    },
    {
      key: 'scope',
      label: 'Scope of Work',
      type: 'rich_text',
      required: true,
      ai_prompt: 'Define the detailed scope of work. Be explicit about what is included and excluded.',
      placeholder: 'In Scope: [list items]. Out of Scope: [list items].',
    },
    {
      key: 'deliverables',
      label: 'Deliverables',
      type: 'list',
      required: true,
      ai_prompt: 'List all concrete deliverables with descriptions. Be specific about format and quality standards.',
      placeholder: 'e.g., API documentation (Markdown), Performance testing report (PDF), Code repository (GitHub)',
    },
    {
      key: 'milestones',
      label: 'Milestones & Payment Schedule',
      type: 'table',
      required: true,
      ai_prompt: 'Create a milestone-based timeline with key deliverables and payment schedule. Format: "Milestone | Date | Deliverables | Payment %"',
      placeholder: 'Milestone 1: Discovery | Week 2 | Requirements doc, Wireframes | 25%\nMilestone 2: Development | Week 6 | Core features | 50%',
    },
    {
      key: 'acceptance_criteria',
      label: 'Acceptance Criteria',
      type: 'rich_text',
      required: true,
      ai_prompt: 'Define clear acceptance criteria for each deliverable. How will Client know deliverables meet expectations?',
      placeholder: 'Design mockups accepted when: approved by stakeholder, meets brand guidelines, responsive design verified.',
    },
    {
      key: 'assumptions',
      label: 'Assumptions',
      type: 'list',
      required: true,
      ai_prompt: 'List key assumptions underlying this SOW. What are we assuming about resources, requirements, or availability?',
      placeholder: 'e.g., Client provides timely feedback, Required data available by [date], Existing systems remain stable',
    },
    {
      key: 'exclusions',
      label: 'Exclusions & Out of Scope',
      type: 'list',
      required: true,
      ai_prompt: 'Clearly list what is NOT included in this SOW to prevent scope creep.',
      placeholder: 'e.g., Hosting/infrastructure setup, Training and knowledge transfer, Ongoing maintenance',
    },
    {
      key: 'change_process',
      label: 'Change Management Process',
      type: 'rich_text',
      required: true,
      ai_prompt: 'Define how change requests are handled. Include approval process, assessment of impact, and change order issuance.',
      placeholder: 'Change requests submitted in writing. Evaluated for impact on timeline/budget. Approved changes require signed change order.',
    },
  ],
  metadata_schema: {
    deliverables: { type: 'array' },
    assumptions: { type: 'array' },
    exclusions: { type: 'array' },
    payment_schedule: { type: 'array' },
  },
};

// ---- Template 6: Product Requirements Doc (Pro) ----
export const TEMPLATE_PRD: Omit<Template, 'id' | 'created_at' | 'updated_at'> = {
  type: 'prd',
  name: 'Product Requirements Document',
  description: 'Detailed PRD with user stories, requirements, and success metrics',
  category: 'development',
  is_system: true,
  freelancer_id: null,
  tier_required: 'pro',
  default_file_type: 'pdf',
  styling: defaultStyling,
  sections: [
    {
      key: 'problem_statement',
      label: 'Problem Statement',
      type: 'rich_text',
      required: true,
      ai_prompt: 'Write a clear problem statement for {project_name}. Describe the pain point and why it matters to {client_name}.',
      placeholder: 'Current challenge: [describe problem]. Impact: [quantify impact]. Root cause: [identify why it exists].',
    },
    {
      key: 'goals',
      label: 'Goals & Vision',
      type: 'list',
      required: true,
      ai_prompt: 'List high-level goals for this product or feature. What success looks like.',
      placeholder: 'e.g., Reduce support ticket volume by 50%, Improve user onboarding time to <5 minutes',
    },
    {
      key: 'user_stories',
      label: 'User Stories',
      type: 'list',
      required: true,
      ai_prompt: 'Write user stories in the format "As a [role], I want to [action], so that [benefit]". Include 5-10 stories covering main flows.',
      placeholder: 'As a user, I want to save my preferences, so that I don\'t have to reconfigure on each visit.',
    },
    {
      key: 'functional_requirements',
      label: 'Functional Requirements',
      type: 'list',
      required: true,
      ai_prompt: 'List specific functional requirements. What must the product do? Format: "System shall [verb] [object] [condition]"',
      placeholder: 'System shall authenticate users via OAuth. System shall display results in <2 seconds.',
    },
    {
      key: 'non_functional_requirements',
      label: 'Non-Functional Requirements',
      type: 'list',
      required: true,
      ai_prompt: 'List non-functional requirements such as performance, security, scalability, and accessibility.',
      placeholder: 'Must load in <3 seconds. Support 1000+ concurrent users. WCAG 2.1 AA accessible. GDPR compliant.',
    },
    {
      key: 'technical_constraints',
      label: 'Technical Constraints',
      type: 'rich_text',
      required: true,
      ai_prompt: 'Describe technical constraints and architecture decisions. Include tech stack, integrations, and limitations.',
      placeholder: 'Must use React + Node.js. Integrate with Stripe API. Support modern browsers. Deploy to AWS.',
    },
    {
      key: 'success_metrics',
      label: 'Success Metrics',
      type: 'list',
      required: true,
      ai_prompt: 'Define measurable KPIs to track success. How will we know this was worth building?',
      placeholder: 'e.g., User adoption rate 40%+, Feature usage 80%+, Support tickets reduced by 50%',
    },
    {
      key: 'timeline',
      label: 'Implementation Timeline',
      type: 'text',
      required: false,
      ai_prompt: 'Provide estimated timeline for development phases.',
      placeholder: 'Phase 1 (4 weeks): MVP. Phase 2 (2 weeks): Testing. Phase 3 (1 week): Launch.',
    },
  ],
  metadata_schema: {
    priority: { type: 'string' },
    target_audience: { type: 'string' },
    success_metrics: { type: 'array' },
    constraints: { type: 'array' },
  },
};

// ---- Template 7: Change Order (Pro+) ----
export const TEMPLATE_CHANGE_ORDER: Omit<Template, 'id' | 'created_at' | 'updated_at'> = {
  type: 'change_order',
  name: 'Change Order',
  description: 'Document changes to scope, timeline, or budget with approval workflow',
  category: 'general',
  is_system: true,
  freelancer_id: null,
  tier_required: 'pro_plus',
  default_file_type: 'pdf',
  styling: defaultStyling,
  sections: [
    {
      key: 'change_description',
      label: 'Change Description',
      type: 'rich_text',
      required: true,
      ai_prompt: 'Clearly describe the proposed change to the {project_name} project. Include what is being added, modified, or removed.',
      placeholder: 'Add integration with Slack API to send daily digest emails. This involves creating a new service module and webhook endpoint.',
    },
    {
      key: 'reason',
      label: 'Reason for Change',
      type: 'rich_text',
      required: true,
      ai_prompt: 'Explain why this change is necessary or beneficial. Reference original project scope or client feedback.',
      placeholder: 'Client feedback indicates users need real-time notifications. This change enhances the value proposition.',
    },
    {
      key: 'impact_scope',
      label: 'Scope Impact',
      type: 'rich_text',
      required: true,
      ai_prompt: 'Describe how this change impacts the project scope. What components are affected?',
      placeholder: 'Impact: Adds 2 new deliverables (Slack integration module, notification service). Affects: API layer, notification system.',
    },
    {
      key: 'impact_timeline',
      label: 'Timeline Impact',
      type: 'text',
      required: true,
      ai_prompt: 'Specify timeline impact. How much additional time is needed?',
      placeholder: 'Estimated additional time: 3 weeks. New completion date: [date]. Affects subsequent milestones.',
    },
    {
      key: 'impact_cost',
      label: 'Cost Impact',
      type: 'currency',
      required: true,
      ai_prompt: 'Calculate the cost of this change. Include labor estimate and any additional resources needed.',
      placeholder: '0',
      default_value: 0,
    },
    {
      key: 'approval',
      label: 'Approval & Authorization',
      type: 'rich_text',
      required: true,
      ai_prompt: 'Include signature blocks for Client and Provider approval of this change order.',
      placeholder: 'Provider: [Name] Date: ____\nClient: [Name] Date: ____\nApproved: [ ] Yes [ ] No',
    },
  ],
  metadata_schema: {
    original_document_id: { type: 'string' },
    cost_impact: { type: 'number' },
    timeline_impact: { type: 'string' },
    reason: { type: 'string' },
  },
};

// ---- Template 8: Meeting Notes (Pro+) ----
export const TEMPLATE_MEETING_NOTES: Omit<Template, 'id' | 'created_at' | 'updated_at'> = {
  type: 'meeting_notes',
  name: 'Meeting Notes',
  description: 'Structured meeting notes with attendees, decisions, and action items',
  category: 'general',
  is_system: true,
  freelancer_id: null,
  tier_required: 'pro_plus',
  default_file_type: 'pdf',
  styling: defaultStyling,
  sections: [
    {
      key: 'attendees',
      label: 'Attendees',
      type: 'list',
      required: true,
      ai_prompt: 'List all meeting attendees with their roles or titles.',
      placeholder: 'e.g., [Your name] (Provider), Client Name (Project Manager), Jane Doe (Designer)',
    },
    {
      key: 'agenda',
      label: 'Agenda',
      type: 'list',
      required: true,
      ai_prompt: 'Outline the meeting agenda items discussed.',
      placeholder: 'e.g., Project status update, Design review, Timeline adjustments, Next steps',
    },
    {
      key: 'discussion_points',
      label: 'Key Discussion Points',
      type: 'list',
      required: true,
      ai_prompt: 'Summarize key points discussed for each agenda item. Capture decisions and concerns.',
      placeholder: 'Design feedback: Approved header layout, need to adjust color scheme. Timeline: On track, no blockers.',
    },
    {
      key: 'decisions',
      label: 'Decisions Made',
      type: 'list',
      required: true,
      ai_prompt: 'List all decisions made during the meeting. Be specific and clear.',
      placeholder: 'e.g., Approved revised design mockups, Decided to launch beta on [date], Approved budget increase for [feature]',
    },
    {
      key: 'action_items',
      label: 'Action Items',
      type: 'list',
      required: true,
      ai_prompt: 'List specific action items with assigned owners and due dates. Format: "Action | Owner | Due Date"',
      placeholder: 'Revise color scheme | Designer | End of week\nProvide API docs | Developer | Next Tuesday\nApprove wireframes | Client | By Friday',
    },
    {
      key: 'next_meeting',
      label: 'Next Meeting',
      type: 'date',
      required: false,
      ai_prompt: 'Specify the date and time of the next scheduled meeting.',
      placeholder: '',
    },
  ],
  metadata_schema: {
    attendees: { type: 'array' },
    agenda_items: { type: 'array' },
    action_items: { type: 'array' },
    next_meeting: { type: 'string', format: 'date-time' },
  },
};

// Export all templates as an array
export const SYSTEM_TEMPLATES: Omit<Template, 'id' | 'created_at' | 'updated_at'>[] = [
  TEMPLATE_STANDARD_PROPOSAL,
  TEMPLATE_SIMPLE_INVOICE,
  TEMPLATE_BASIC_CONTRACT,
  TEMPLATE_PROJECT_BRIEF,
  TEMPLATE_DETAILED_SOW,
  TEMPLATE_PRD,
  TEMPLATE_CHANGE_ORDER,
  TEMPLATE_MEETING_NOTES,
];
