import { createClient } from '@/lib/supabase/server';
import { NextResponse } from 'next/server';

export type GraphNode = {
  id: string;
  title: string;
  contentLength: number;
  createdAt: string;
  updatedAt: string;
  tags: string[];
};

export type GraphLink = {
  source: string;
  target: string;
  autoGenerated: boolean;
};

export type GraphData = {
  nodes: GraphNode[];
  links: GraphLink[];
};

/**
 * GET /api/graph
 * Returns the full graph data for the terrarium visualization
 */
export async function GET() {
  try {
    const supabase = await createClient();

    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser();

    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Fetch notes
    const { data: notes, error: notesError } = await supabase
      .from('notes')
      .select('id, title, content, created_at, updated_at')
      .eq('user_id', user.id)
      .eq('is_archived', false)
      .order('updated_at', { ascending: false });

    if (notesError) throw notesError;

    // Fetch links between user's notes
    const noteIds = (notes || []).map((n) => n.id);

    let links: { source_note_id: string; target_note_id: string; auto_generated: boolean }[] = [];
    if (noteIds.length > 0) {
      const { data: linkData, error: linksError } = await supabase
        .from('links')
        .select('source_note_id, target_note_id, auto_generated')
        .in('source_note_id', noteIds)
        .in('target_note_id', noteIds)
        .eq('dismissed', false);

      if (linksError) throw linksError;
      links = linkData || [];
    }

    // Fetch tags
    let tagMap: Record<string, string[]> = {};
    if (noteIds.length > 0) {
      const { data: tagData, error: tagsError } = await supabase
        .from('tags')
        .select('note_id, tag')
        .in('note_id', noteIds);

      if (!tagsError && tagData) {
        for (const t of tagData) {
          if (!tagMap[t.note_id]) tagMap[t.note_id] = [];
          tagMap[t.note_id].push(t.tag);
        }
      }
    }

    const graphData: GraphData = {
      nodes: (notes || []).map((n) => ({
        id: n.id,
        title: n.title || 'Untitled',
        contentLength: (n.content || '').length,
        createdAt: n.created_at,
        updatedAt: n.updated_at,
        tags: tagMap[n.id] || [],
      })),
      links: links.map((l) => ({
        source: l.source_note_id,
        target: l.target_note_id,
        autoGenerated: l.auto_generated,
      })),
    };

    return NextResponse.json(graphData);
  } catch (error) {
    console.error('GET /api/graph error:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}
